# Generated by Django 5.2.16 on 2026-07-31 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=2000)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scraping', 'Scraping'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('meta_description', models.TextField(blank=True)),
                ('raw_html', models.TextField(blank=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('url',), name='unique_url')],
            },
        ),
        migrations.CreateModel(
            name='ContentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('token_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='kbapp.harvestedurl')),
            ],
            options={
                'ordering': ['url_id', 'chunk_index'],
                'constraints': [models.UniqueConstraint(fields=('url', 'chunk_index'), name='unique_url_chunk')],
            },
        ),
    ]
